version: '3'
services: 
    redis-server:
        image: 'redis:alpine'
        command: redis-server --requirepass mozart
        ports: 
            - "6379:6379"
        deploy:
            replicas: 1
            restart_policy:
              condition: on-failure
    wopi:
        image: drivedocs/drivewopi
        depends_on:
            - redis-server
        environment:
            -  REDIS_HOST=13.74.150.126
            -  REDIS_PORT=6379
            -  DRIVE_URL=http://yosef.northeurope.cloudapp.azure.com
            -  PORT=8080
            -  JWT_SECRET=niceSecret
            -  FOLDER=/sample_files
            -  TEMPLATE_FOLDER=/templates
            -  AUTHORIZATION_TOKEN=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlNTY4ODMyNDIwM2ZjNDAwNDM1OTFhYSIsImFkZnNJZCI6InQyMzQ1ODc4OUBqZWxsby5jb20iLCJnZW5lc2lzSWQiOiI1ZTU2ODgzMjQyMDNmYzQwMDQzNTkxYWEiLCJuYW1lIjp7ImZpcnN0TmFtZSI6Iteg15nXmden15kiLCJsYXN0TmFtZSI6IteQ15PXmdeT16EifSwiZGlzcGxheU5hbWUiOiJ0MjM0NTg3ODlAamVsbG8uY29tIiwicHJvdmlkZXIiOiJHZW5lc2lzIiwiZW50aXR5VHlwZSI6ImRpZ2ltb24iLCJjdXJyZW50VW5pdCI6Im5pdHJvIHVuaXQiLCJkaXNjaGFyZ2VEYXkiOiIyMDIyLTExLTMwVDIyOjAwOjAwLjAwMFoiLCJyYW5rIjoibWVnYSIsImpvYiI6Iteo15XXpteXIiwicGhvbmVOdW1iZXJzIjpbIjA1Mi0xMjM0NTY3Il0sImFkZHJlc3MiOiLXqNeX15XXkSDXlNee157Xqten15nXnSAzNCIsInBob3RvIjpudWxsLCJqdGkiOiI0YzRmMzYwMS00OTQ0LTQ3M2MtOTEyMi1hNjVjMGU5YmI0YWUiLCJpYXQiOjE1OTQxMDE0NjksImV4cCI6MTU5NjY5MzQ2OSwiZmlyc3ROYW1lIjoi16DXmdeZ16fXmSIsImxhc3ROYW1lIjoi15DXk9eZ15PXoSJ9.QlEuP5nO8S7uZ7P66RtMOTWABRRFAA11dER03SI2KQk
            -  DRIVE_SECRET=krypton@drive
            -  TOKEN_EXPIRE=86400000
            -  TIME_OUT=30000 #Time period to perform cleanUp in milliseconds
            -  CLOSE_WAIT=3600 #Time before the session is deleted after not being updated in seconds
            -  REMOVE_WAIT_USER=1200 #Time before the user is deleted from the session after begin inactive in seconds
            -  MAX_REDIS_SESSION_TIME=86400 #maximum time for session on redis
            -  DRIVE_UPDATE_TIME=30
            -  REDIS_PASSWORD=mozart

        ports: 
            - "8082:8080"
        volumes:
            - ./sample_files:/sample_files
            - ./templates:/templates
        deploy:
            replicas: 1
            restart_policy:
              condition: on-failure
    node-app:
        image: drivedocs/driveofficeeditor
        environment:
            -  WOPI_URL=http://13.74.150.126:8082
            -  REDIS_HOST=13.74.150.126
            -  REDIS_PORT=6379
            -  OFFICE_ONLINE_URL=http://52.178.147.179
            -  PORT=3000
            -  OFFICE_EDITOR_URL=http://13.79.160.153:3000
            -  JWT_SECRET=niceSecret
            -  SHRAGA_URL=http://13.79.7.3
            -  AUTHORIZATION_TOKEN=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlNTY4ODMyNDIwM2ZjNDAwNDM1OTFhYSIsImFkZnNJZCI6InQyMzQ1ODc4OUBqZWxsby5jb20iLCJnZW5lc2lzSWQiOiI1ZTU2ODgzMjQyMDNmYzQwMDQzNTkxYWEiLCJuYW1lIjp7ImZpcnN0TmFtZSI6Iteg15nXmden15kiLCJsYXN0TmFtZSI6IteQ15PXmdeT16EifSwiZGlzcGxheU5hbWUiOiJ0MjM0NTg3ODlAamVsbG8uY29tIiwicHJvdmlkZXIiOiJHZW5lc2lzIiwiZW50aXR5VHlwZSI6ImRpZ2ltb24iLCJjdXJyZW50VW5pdCI6Im5pdHJvIHVuaXQiLCJkaXNjaGFyZ2VEYXkiOiIyMDIyLTExLTMwVDIyOjAwOjAwLjAwMFoiLCJyYW5rIjoibWVnYSIsImpvYiI6Iteo15XXpteXIiwicGhvbmVOdW1iZXJzIjpbIjA1Mi0xMjM0NTY3Il0sImFkZHJlc3MiOiLXqNeX15XXkSDXlNee157Xqten15nXnSAzNCIsInBob3RvIjpudWxsLCJqdGkiOiI0YzRmMzYwMS00OTQ0LTQ3M2MtOTEyMi1hNjVjMGU5YmI0YWUiLCJpYXQiOjE1OTQxMDE0NjksImV4cCI6MTU5NjY5MzQ2OSwiZmlyc3ROYW1lIjoi16DXmdeZ16fXmSIsImxhc3ROYW1lIjoi15DXk9eZ15PXoSJ9.QlEuP5nO8S7uZ7P66RtMOTWABRRFAA11dER03SI2KQk
            -  DRIVE_URL=http://yosef.northeurope.cloudapp.azure.com
            # - 'SECRET=thisIsASecret'
            -  DRIVE_SECRET=krypton@drive
            -  REDIS_PASSWORD=mozart

        depends_on:
            - redis-server
            - wopi
        ports: 
            - "3000:3000"
        deploy:
            replicas: 1
            restart_policy:
              condition: on-failure
