version: '3'
services: 
    redis-server:
        image: 'redis'
        container_name: redis-server
        ports: 
            - "6379:6379"
    wopi:
        build: ./DriveWopi/DriveWopi
        depends_on:
            - redis-server
        environment:
            - 'REDIS_HOST=13.79.160.153:6379'
            #- 'DRIVE_URL=http://test-sh.northeurope.cloudapp.azure.com'
            - 'DRIVE_URL=http://yosef.northeurope.cloudapp.azure.com'
            - 'PORT=8080'
            - 'JWT_SECRET=niceSecret'
            - 'FOLDER=/sample_files'
            - 'TEMPLATE_FOLDER=/templates'
            - 'AUTHORIZATION_TOKEN=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlNTY4ODMyNDIwM2ZjNDAwNDM1OTFhYSIsImFkZnNJZCI6InQyMzQ1ODc4OUBqZWxsby5jb20iLCJnZW5lc2lzSWQiOiI1ZTU2ODgzMjQyMDNmYzQwMDQzNTkxYWEiLCJuYW1lIjp7ImZpcnN0TmFtZSI6Iteg15nXmden15kiLCJsYXN0TmFtZSI6IteQ15PXmdeT16EifSwiZGlzcGxheU5hbWUiOiJ0MjM0NTg3ODlAamVsbG8uY29tIiwicHJvdmlkZXIiOiJHZW5lc2lzIiwiZW50aXR5VHlwZSI6ImRpZ2ltb24iLCJjdXJyZW50VW5pdCI6Im5pdHJvIHVuaXQiLCJkaXNjaGFyZ2VEYXkiOiIyMDIyLTExLTMwVDIyOjAwOjAwLjAwMFoiLCJyYW5rIjoibWVnYSIsImpvYiI6Iteo15XXpteXIiwicGhvbmVOdW1iZXJzIjpbIjA1Mi0xMjM0NTY3Il0sImFkZHJlc3MiOiLXqNeX15XXkSDXlNee157Xqten15nXnSAzNCIsInBob3RvIjpudWxsLCJqdGkiOiJkNjg4ZjE5Yi03M2RkLTQzZmYtYTg0Ny0wNmYxYWQyMTI0NjQiLCJpYXQiOjE1OTM0MzIzNDUsImV4cCI6MTU5NjAyNDM0NSwiZmlyc3ROYW1lIjoi16DXmdeZ16fXmSIsImxhc3ROYW1lIjoi15DXk9eZ15PXoSJ9.H2x6rM3h7gJyR4bUkJ9CdjlsQm83TGNVI1nlqIuVpSQ'
            - 'DRIVE_SECRET=driveSecret'
            - 'TOKEN_EXPIRE=86400000'
            #Time period to perform cleanUp in milliseconds
            - 'TIME_OUT=30000'
            #Time before the session is deleted after not being updated in seconds
            - 'CLOSE_WAIT=60'
            #Time before the user is deleted from the session after begin inactive in seconds
            - 'REMOVE_WAIT_USER=1800'
        ports: 
            - "8082:8080"
        volumes:
            - ./sample_files:/sample_files
            - ./templates:/templates
    node-app:
        build: ./DriveOfficeEditor
        environment:
            - 'WOPI_URL=http://13.79.160.153:8082'
            - 'REDIS_HOST=13.79.160.153'
            - 'REDIS_PORT=6379'
            - 'OFFICE_ONLINE_URL=http://52.178.147.179'
            - 'PORT=3000'
            - 'JWT_SECRET=niceSecret'
            - 'SHRAGA_URL=http://13.79.7.3'
            - 'AUTHORIZATION_TOKEN=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlNTY4ODMyNDIwM2ZjNDAwNDM1OTFhYSIsImFkZnNJZCI6InQyMzQ1ODc4OUBqZWxsby5jb20iLCJnZW5lc2lzSWQiOiI1ZTU2ODgzMjQyMDNmYzQwMDQzNTkxYWEiLCJuYW1lIjp7ImZpcnN0TmFtZSI6Iteg15nXmden15kiLCJsYXN0TmFtZSI6IteQ15PXmdeT16EifSwiZGlzcGxheU5hbWUiOiJ0MjM0NTg3ODlAamVsbG8uY29tIiwicHJvdmlkZXIiOiJHZW5lc2lzIiwiZW50aXR5VHlwZSI6ImRpZ2ltb24iLCJjdXJyZW50VW5pdCI6Im5pdHJvIHVuaXQiLCJkaXNjaGFyZ2VEYXkiOiIyMDIyLTExLTMwVDIyOjAwOjAwLjAwMFoiLCJyYW5rIjoibWVnYSIsImpvYiI6Iteo15XXpteXIiwicGhvbmVOdW1iZXJzIjpbIjA1Mi0xMjM0NTY3Il0sImFkZHJlc3MiOiLXqNeX15XXkSDXlNee157Xqten15nXnSAzNCIsInBob3RvIjpudWxsLCJqdGkiOiJkNjg4ZjE5Yi03M2RkLTQzZmYtYTg0Ny0wNmYxYWQyMTI0NjQiLCJpYXQiOjE1OTM0MzIzNDUsImV4cCI6MTU5NjAyNDM0NSwiZmlyc3ROYW1lIjoi16DXmdeZ16fXmSIsImxhc3ROYW1lIjoi15DXk9eZ15PXoSJ9.H2x6rM3h7gJyR4bUkJ9CdjlsQm83TGNVI1nlqIuVpSQ'
            - 'DRIVE_URL=http://yosef.northeurope.cloudapp.azure.com'
            #- 'DRIVE_URL=http://ea6d4bb59438.ngrok.io'
            - 'SECRET=thisIsASecret'
            - 'DRIVE_SECRET=driveSecret'

        depends_on:
            - redis-server
            - wopi
        ports: 
            - "3000:3000"